In [15]:
#import pandas module for creating dataframe
import pandas as pd

In [16]:
#read CSV into DataFrame
data = pd.read_csv("smsspamcollection.csv",encoding="ISO-8859-1")
data

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [17]:
#import string module for string manipulation
import string

In [18]:
#defining the function to remove punctuations in the documents
def remove_punctuation(text):
    punctuationfree = "".join([i for i in text if i not in string.punctuation])
    return punctuationfree
    #Initialize an empty string to store the result
    punctuation_free = ""
    
    # Iterate over each character in the text
    for i in text:
        # Check if the character is not in the string.punctuation set
        if i not in string.punctuation:
            # If not, add the character to the result string
            punctuation_free += i
    
    return punctuation_free

In [19]:
data['clean_punctuation']= data['v2'].apply(remove_punctuation)
data

,v1,v2,clean_punctuation
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...
...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,This is the 2nd time we have tried 2 contact u...
5568,ham,Will Ì_ b going to esplanade fr home?,Will Ì b going to esplanade fr home
5569,ham,"Pity, * was in mood for that. So...any other s...",Pity was in mood for that Soany other suggest...
5570,ham,The guy did some bitching but I acted like i'd...,The guy did some bitching but I acted like id ...
5571,ham,Rofl. Its true to its name,Rofl Its true to its name

In [20]:
#to standardize the cases in the documents into lower case
data['clean_lower']= data['clean_punctuation'].str.lower()
data

,v1,v2,clean_punctuation,clean_lower
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go until jurong point crazy available only in ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,u dun say so early hor u c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah i dont think he goes to usf he lives aroun...
...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,This is the 2nd time we have tried 2 contact u...,this is the 2nd time we have tried 2 contact u...
5568,ham,Will Ì_ b going to esplanade fr home?,Will Ì b going to esplanade fr home,will ì b going to esplanade fr home
5569,ham,"Pity, * was in mood for that. So...any other s...",Pity was in mood for that Soany other suggest...,pity was in mood for that soany other suggest...
5570,ham,The guy did some bitching but I acted like i'd...,The guy did some bitching but I acted like id ...,the guy did some bitching but i acted like id ...
5571,ham,Rofl. Its true to its name,Rofl Its true to its name,rofl its true to its name

In [21]:
#import regular expression library
import re

In [22]:
#function to remove digit (\d) or hypens (-) from the documents with an empty string ''
def remove_numbers(text):
    return re.sub("[\d-]",'',text)
#applying the remove_numbers function to the 'clean_lower' column and storing the result in a new column 'clean_number'
data['clean_number'] = data['clean_lower'].apply(remove_numbers)
data

,v1,v2,clean_punctuation,clean_lower,clean_number
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go until jurong point crazy available only in ...,go until jurong point crazy available only in ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif u oni,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...,free entry in a wkly comp to win fa cup final...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,u dun say so early hor u c already then say,u dun say so early hor u c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah i dont think he goes to usf he lives aroun...,nah i dont think he goes to usf he lives aroun...
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,This is the 2nd time we have tried 2 contact u...,this is the 2nd time we have tried 2 contact u...,this is the nd time we have tried contact u u...
5568,ham,Will Ì_ b going to esplanade fr home?,Will Ì b going to esplanade fr home,will ì b going to esplanade fr home,will ì b going to esplanade fr home
5569,ham,"Pity, * was in mood for that. So...any other s...",Pity was in mood for that Soany other suggest...,pity was in mood for that soany other suggest...,pity was in mood for that soany other suggest...
5570,ham,The guy did some bitching but I acted like i'd...,The guy did some bitching but I acted like id ...,the guy did some bitching but i acted like id ...,the guy did some bitching but i acted like id ...
5571,ham,Rofl. Its true to its name,Rofl Its true to its name,rofl its true to its name,rofl its true to its name

In [23]:
#import Natural Language Processing (NLP) library called 
#Natural Language Toolkit (NLTK)
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [24]:
# import the library for word tokenization
from nltk.tokenize import word_tokenize

#the word tokens in the document
data['token_data']= data['clean_number'].apply(word_tokenize)
data

,v1,v2,clean_punctuation,clean_lower,clean_number,token_data
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go until jurong point crazy available only in ...,go until jurong point crazy available only in ...,"[go, until, jurong, point, crazy, available, o..."
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif u oni,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...,free entry in a wkly comp to win fa cup final...,"[free, entry, in, a, wkly, comp, to, win, fa, ..."
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,u dun say so early hor u c already then say,u dun say so early hor u c already then say,"[u, dun, say, so, early, hor, u, c, already, t..."
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah i dont think he goes to usf he lives aroun...,nah i dont think he goes to usf he lives aroun...,"[nah, i, dont, think, he, goes, to, usf, he, l..."
...,...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,This is the 2nd time we have tried 2 contact u...,this is the 2nd time we have tried 2 contact u...,this is the nd time we have tried contact u u...,"[this, is, the, nd, time, we, have, tried, con..."
5568,ham,Will Ì_ b going to esplanade fr home?,Will Ì b going to esplanade fr home,will ì b going to esplanade fr home,will ì b going to esplanade fr home,"[will, ì, b, going, to, esplanade, fr, home]"
5569,ham,"Pity, * was in mood for that. So...any other s...",Pity was in mood for that Soany other suggest...,pity was in mood for that soany other suggest...,pity was in mood for that soany other suggest...,"[pity, was, in, mood, for, that, soany, other,..."
5570,ham,The guy did some bitching but I acted like i'd...,The guy did some bitching but I acted like id ...,the guy did some bitching but i acted like id ...,the guy did some bitching but i acted like id ...,"[the, guy, did, some, bitching, but, i, acted,..."
5571,ham,Rofl. Its true to its name,Rofl Its true to its name,rofl its true to its name,rofl its true to its name,"[rofl, its, true, to, its, name]"

In [28]:
# Checking Duplicate values
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   v1                 5572 non-null   object
 1   v2                 5572 non-null   object
 2   clean_punctuation  5572 non-null   object
 3   clean_lower        5572 non-null   object
 4   clean_number       5572 non-null   object
 5   token_data         5572 non-null   object
dtypes: object(6)
memory usage: 261.3+ KB

In [30]:
# Checking for null values
data.isnull().sum()

v1                   0
v2                   0
clean_punctuation    0
clean_lower          0
clean_number         0
token_data           0
dtype: int64

In [32]:
# Function to convert lists to strings
def convert_lists_to_strings(value):
    if isinstance(value, list):
        return ','.join(map(str, value))
    else:
        return value

# Apply the conversion function to all columns in the DataFrame
data = data.applymap(convert_lists_to_strings)

# Now you can use the duplicated method
duplicates = data.duplicated()
num_duplicates = duplicates.sum()
print("Number of duplicates:", num_duplicates)

Number of duplicates: 403

In [34]:
# Drop Duplicate values
data=data.drop_duplicates()
data.shape

(5169, 6)

In [38]:
# renaming the columns
data.columns.values[:2] = ['label', 'message']
data

,label,message,clean_punctuation,clean_lower,clean_number,token_data
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go until jurong point crazy available only in ...,go until jurong point crazy available only in ...,"go,until,jurong,point,crazy,available,only,in,..."
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif u oni,ok lar joking wif u oni,"ok,lar,joking,wif,u,oni"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...,free entry in a wkly comp to win fa cup final...,"free,entry,in,a,wkly,comp,to,win,fa,cup,final,..."
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,u dun say so early hor u c already then say,u dun say so early hor u c already then say,"u,dun,say,so,early,hor,u,c,already,then,say"
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah i dont think he goes to usf he lives aroun...,nah i dont think he goes to usf he lives aroun...,"nah,i,dont,think,he,goes,to,usf,he,lives,aroun..."
...,...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,This is the 2nd time we have tried 2 contact u...,this is the 2nd time we have tried 2 contact u...,this is the nd time we have tried contact u u...,"this,is,the,nd,time,we,have,tried,contact,u,u,..."
5568,ham,Will Ì_ b going to esplanade fr home?,Will Ì b going to esplanade fr home,will ì b going to esplanade fr home,will ì b going to esplanade fr home,"will,ì,b,going,to,esplanade,fr,home"
5569,ham,"Pity, * was in mood for that. So...any other s...",Pity was in mood for that Soany other suggest...,pity was in mood for that soany other suggest...,pity was in mood for that soany other suggest...,"pity,was,in,mood,for,that,soany,other,suggestions"
5570,ham,The guy did some bitching but I acted like i'd...,The guy did some bitching but I acted like id ...,the guy did some bitching but i acted like id ...,the guy did some bitching but i acted like id ...,"the,guy,did,some,bitching,but,i,acted,like,id,..."
5571,ham,Rofl. Its true to its name,Rofl Its true to its name,rofl its true to its name,rofl its true to its name,"rofl,its,true,to,its,name"